// ═══════════════════════════════════════════════════════════════
//  AASHISH KE SAARE POSTS — YAHAN ADD KARO
//
//  aspect: 'portrait'  → Reels/Stories (9:16 tall)
//          'square'    → Instagram Posts (1:1)
//          'landscape' → Videos/YouTube (16:9 wide)
//          'wide'      → Cinematic (21:9 extra wide)
//
//  thumb:  Post ki thumbnail image URL (Instagram/YouTube se copy karo)
//          Khaali '' rakho — stylish gradient auto dikhega
//
//  postUrl: Direct link — click karne par seedha wahan jayega
// ═══════════════════════════════════════════════════════════════

export type Post = {
  id: string
  cat: string
  platform: 'instagram' | 'youtube' | 'facebook'
  postUrl: string
  thumb: string
  aspect: 'portrait' | 'square' | 'landscape' | 'wide'
}

export const POSTS: Post[] = [
  {
    id: 'reel-001',
    cat: 'Reels',
    platform: 'instagram',
    postUrl: 'https://www.instagram.com/reel/DVsjSElDBiK/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781158135/Image-575_vbrmu1.jpg',
    aspect: 'portrait',
  },
  {
    id: 'reel-002',
    cat: 'Reels',
    platform: 'instagram',
    postUrl: 'https://www.instagram.com/reel/DM9kFvxNX5E/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781159831/Image-587_utk2pu.jpg',
    aspect: 'portrait',
  },
  {
    id: 'reel-003',
    cat: 'Reels',
    platform: 'instagram',
    postUrl: 'https://www.instagram.com/reel/DMX_thDP7H1/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781162337/Image-643_xhd52q.jpg',
    aspect: 'portrait',
  },
  {
    id: 'reel-004',
    cat: 'Reels',
    platform: 'instagram',
    postUrl: 'https://www.instagram.com/reel/DMMuu3esKrm/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781164000/Image-505_jvqptm.jpg',
    aspect: 'portrait',
  },
  {
    id: 'reel-005',
    cat: 'Motion & Animation',
    platform: 'instagram',
    postUrl: 'https://www.instagram.com/reel/DZXrbjuKJQq/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781173035/Image-108_swiu5c.jpg',
    aspect: 'portrait',
  },
  {
    id: 'reel-006',
    cat: 'Reels',
    platform: 'instagram',
    postUrl: 'https://www.instagram.com/reel/DY4eKqeKfKb/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781173188/Image-802_icfcot.jpg',
    aspect: 'portrait',
  },
  {
    id: 'reel-007',
    cat: 'Reels',
    platform: 'instagram',
    postUrl: 'https://www.instagram.com/reel/DXwcrh2KdtF/?utm_source=ig_web_button_share_sheet',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781337851/Image-332_nlzglf.jpg',
    aspect: 'portrait',
  },
  {
    id: 'post-001',
    cat: 'Content Creation',
    platform: 'instagram',
    postUrl: 'https://www.instagram.com/p/APNA_POST_ID/',
    thumb: '',
    aspect: 'square',
  },
  {
    id: 'video-001',
    cat: 'Video Production',
    platform: 'youtube',
    postUrl: 'https://www.youtube.com/watch?v=7wZzD9bdkAo&t=578s',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781340294/7wZzD9bdkAo-SD_encwdy.jpg',
    aspect: 'landscape',
  },
  {
    id: 'meta-001',
    cat: 'Meta Ads',
    platform: 'facebook',
    postUrl: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781339843/WhatsApp_Image_2026-06-11_at_15.39.24_lkquj8.jpg',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781339843/WhatsApp_Image_2026-06-11_at_15.39.24_lkquj8.jpg',
    aspect: 'landscape',
  },
  {
    id: 'meta-002',
    cat: 'Meta Ads',
    platform: 'instagram',
    postUrl: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781339843/WhatsApp_Image_2026-06-11_at_15.40.55_1_xxeagq.jpg',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781339843/WhatsApp_Image_2026-06-11_at_15.40.55_1_xxeagq.jpg',
    aspect: 'square',
  },
  {
    id: 'meta-003',
    cat: 'Meta Ads',
    platform: 'instagram',
    postUrl: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781339844/WhatsApp_Image_2026-06-11_at_15.40.55_2_tff9ys.jpg',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781339844/WhatsApp_Image_2026-06-11_at_15.40.55_2_tff9ys.jpg',
    aspect: 'square',
  },
  {
    id: 'meta-004',
    cat: 'Meta Ads',
    platform: 'instagram',
    postUrl: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781339844/WhatsApp_Image_2026-06-11_at_15.40.55_dwtm37.jpg',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781339844/WhatsApp_Image_2026-06-11_at_15.40.55_dwtm37.jpg',
    aspect: 'square',
  },
  {
    id: 'reel-004',
    cat: 'Reels',
    platform: 'instagram',
    postUrl: 'https://www.instagram.com/reel/DEkdYrQS_CM/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781164176/Image-172_ppnfom.jpg',
    aspect: 'portrait',
  },
  {
    id: 'google-001',
    cat: 'Google Ads',
    platform: 'youtube',
    postUrl: 'https://www.youtube.com/watch?v=APNA_VIDEO_ID',
    thumb: '',
    aspect: 'landscape',
  },
  {
    id: 'brand-001',
    cat: 'Graphic Design',
    platform: 'instagram',
    postUrl: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781338875/Social_Media_Design.jpg_i4qvgl.jpg',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781338875/Social_Media_Design.jpg_i4qvgl.jpg',
    aspect: 'square',
  },
  {
    id: 'brand-004',
    cat: 'Brand Identity',
    platform: 'instagram',
    postUrl: 'https://www.instagram.com/reel/DQ1o-LJCMHz/?utm_source=ig_web_button_share_sheet',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781165075/Image-580_zfx3rk.jpg',
    aspect: 'square',
  },
  {
    id: 'brand-005',
    cat: 'Brand Identity',
    platform: 'instagram',
    postUrl: 'https://www.instagram.com/reel/DOd3UNsDEzl/?utm_source=ig_web_button_share_sheet',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781165982/Image-509_fhvbnh.jpg',
    aspect: 'square',
  },
  {
    id: 'brand-006',
    cat: 'Brand Identity',
    platform: 'instagram',
    postUrl: 'https://www.instagram.com/reel/DQosqYKiFyd/?utm_source=ig_web_button_share_sheet',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781166502/Image-537_fqa5j6.jpg',
    aspect: 'square',
  },
  {
    id: 'brand-007',
    cat: 'Motion & Animation',
    platform: 'instagram',
    postUrl: 'https://www.instagram.com/reel/DQ1RHdGjF4c/?utm_source=ig_web_button_share_sheet',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781170385/Image-946_egkrdg.jpg',
    aspect: 'square',
  },
  {
    id: 'brand-008',
    cat: 'Brand Identity',
    platform: 'instagram',
    postUrl: 'https://www.instagram.com/reel/DQopY99Emy0/?utm_source=ig_web_button_share_sheet',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781170797/Image-725_oboktm.jpg',
    aspect: 'square',
  },
  {
    id: 'brand-009',
    cat: 'Brand Identity',
    platform: 'instagram',
    postUrl: 'https://www.instagram.com/reel/DQ69OrPiJox/?utm_source=ig_web_button_share_sheet',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781170964/Image-894_yfrssf.jpg',
    aspect: 'square',
  },
  {
    id: 'content-001',
    cat: 'Content Creation',
    platform: 'instagram',
    postUrl: 'https://www.instagram.com/p/APNA_POST_ID/',
    thumb: '',
    aspect: 'square',
  },
  {
    id: 'film-001',
    cat: 'Film Direction',
    platform: 'instagram',
    postUrl: '',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781328382/WhatsApp_Image_2026-06-13_at_10.40.55_ftdixt.jpg',
    aspect: 'landscape',
  },
  {
    id: 'film-002',
    cat: 'Film Direction',
    platform: 'instagram',
    postUrl: '',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781329763/WhatsApp_Image_2026-06-13_at_11.02.48_bow8y2.jpg',
    aspect: 'landscape',
  },
  {
    id: 'film-003',
    cat: 'Film Direction',
    platform: 'instagram',
    postUrl: 'https://res.cloudinary.com/dppcmxdhi/video/upload/v1781329403/WhatsApp_Video_2026-06-13_at_10.40.57_mqstxm.mp4',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781329764/WhatsApp_Image_2026-06-13_at_11.02.49_1_r5lb4h.jpg',
    aspect: 'landscape',
  },
  {
    id: 'film-004',
    cat: 'Film Direction',
    platform: 'instagram',
    postUrl: '',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781329519/WhatsApp_Image_2026-06-13_at_10.40.55_1_jqjqkb.jpg',

    aspect: 'landscape',
  },
  {
    id: 'film-005',
    cat: 'Film Direction',
    platform: 'instagram',
    postUrl: '',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781328382/WhatsApp_Image_2026-06-13_at_10.40.55_ftdixt.jpg',

    aspect: 'landscape',
  },
  {
    id: 'film-006',
    cat: 'Film Direction',
    platform: 'instagram',
    postUrl: '',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781329767/WhatsApp_Image_2026-06-13_at_11.02.53_rdb6dx.jpg',
    aspect: 'landscape',
  },
  {
    id: 'film-007',
    cat: 'Film Direction',
    platform: 'instagram',
    postUrl: '',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781329767/WhatsApp_Image_2026-06-13_at_11.02.52_lscyit.jpg',
    aspect: 'landscape',
  },
  {
    id: 'film-008',
    cat: 'Film Direction',
    platform: 'instagram',
    postUrl: '',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781329765/WhatsApp_Image_2026-06-13_at_11.02.52_2_nnt0nh.jpg',
    aspect: 'landscape',
  },
  {
    id: 'film-010',
    cat: 'Film Direction',
    platform: 'instagram',
    postUrl: '',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781328382/WhatsApp_Image_2026-06-13_at_10.40.55_ftdixt.jpg',
    aspect: 'landscape',
  },
  {
    id: 'film-011',
    cat: 'Film Direction',
    platform: 'instagram',
    postUrl: '',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781329764/WhatsApp_Image_2026-06-13_at_11.02.52_1_fchgu2.jpg',
    aspect: 'landscape',
  },
  {
    id: 'film-012',
    cat: 'Film Direction',
    platform: 'instagram',
    postUrl: '',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781329764/WhatsApp_Image_2026-06-13_at_11.02.51_gbdk4x.jpg',

    aspect: 'landscape',
  },
  {
    id: 'film-013',
    cat: 'Film Direction',
    platform: 'instagram',
    postUrl: '',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781329764/WhatsApp_Image_2026-06-13_at_11.02.50_smksit.jpg',

    aspect: 'landscape',
  },
  {
    id: 'film-014',
    cat: 'Film Direction',
    platform: 'instagram',
    postUrl: '',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781329764/WhatsApp_Image_2026-06-13_at_11.02.49_wf9wkc.jpg',
    aspect: 'landscape',
  },
  {
    id: 'film-015',
    cat: 'Film Direction',
    platform: 'instagram',
    postUrl: '',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781329764/WhatsApp_Image_2026-06-13_at_11.02.48_1_gag67o.jpg',
    aspect: 'landscape',
  },
  {
    id: 'film-016',
    cat: 'Film Direction',
    platform: 'instagram',
    postUrl: '',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781329763/WhatsApp_Image_2026-06-13_at_11.02.50_1_hbtmkq.jpg',
    aspect: 'landscape',
  },
  {
    id: 'film-017',
    cat: 'Film Direction',
    platform: 'instagram',
    postUrl: '',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781329762/WhatsApp_Image_2026-06-13_at_11.02.47_kcse0u.jpg',
    aspect: 'landscape',
  },
  {
    id: 'film-018',
    cat: 'Film Direction',
    platform: 'instagram',
    postUrl: 'https://res.cloudinary.com/dppcmxdhi/video/upload/v1781329403/WhatsApp_Video_2026-06-13_at_10.40.57_mqstxm.mp4',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781338732/frame-00-00_oexmst.jpg',
    aspect: 'landscape',
  },
  {
    id: 'film-001',
    cat: 'AI Workflow',
    platform: 'instagram',
    postUrl: 'https://res.cloudinary.com/dppcmxdhi/video/upload/v1781333174/WhatsApp_Video_2026-06-11_at_15.41.30_x9kic4.mp4',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781334667/Screenshot_2026-06-13_124042_zqmgqg.png',
    aspect: 'landscape',
  },
  {
    id: 'film-002',
    cat: 'AI Workflow',
    platform: 'instagram',
    postUrl: 'https://res.cloudinary.com/dppcmxdhi/video/upload/v1781339090/WhatsApp_Video_2026-06-13_at_13.39.18_dkbzdl.mp4',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781339105/frame-00-00_nuxn9n.png',
    aspect: 'landscape',
  },
  {
    id: 'film-003',
    cat: 'AI Workflow',
    platform: 'instagram',
    postUrl: 'https://res.cloudinary.com/dppcmxdhi/video/upload/v1781339744/WhatsApp_Video_2026-06-11_at_15.39.24_w2r5qe.mp4',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781339761/frame-00-00_2_bol86x.png',
    aspect: 'landscape',
  },
]

export const CATS = [
  'Reels',
  'Video Production',
  'Meta Ads',
  'Graphic Design',
  'Brand Identity',
  'Motion & Animation',
  'AI Workflow',
  'Film Direction',
]
